roman_number(mmmmdclxxii).
roman_number(mmdccclxxxiii).
roman_number(mmmdlxviiii).
roman_number(mmmmdxcv).
roman_number(dccclxxii).
roman_number(mmcccvi).
roman_number(mmmcdlxxxvii).
roman_number(mmmmccxxi).
roman_number(mmmccxx).
roman_number(mmmmdccclxxiii).
roman_number(mmmccxxxvii).
roman_number(mmccclxxxxix).
roman_number(mdcccxxiiii).
roman_number(mmcxcvi).
roman_number(ccxcviii).
roman_number(mmmcccxxxii).
roman_number(mdccxxx).
roman_number(mmmdcccl).
roman_number(mmmmcclxxxvi).
roman_number(mmdcccxcvi).
roman_number(mmmdcii).
roman_number(mmmccxii).
roman_number(mmmmdcccci).
roman_number(mmdcccxcii).
roman_number(mdcxx).
roman_number(cmlxxxvii).
roman_number(mmmxxi).
roman_number(mmmmcccxiv).
roman_number(mlxxii).
roman_number(mcclxxviiii).
roman_number(mmmmccxxxxi).
roman_number(mmdccclxxii).
roman_number(mmmmxxxi).
roman_number(mmmdcclxxx).
roman_number(mmdccclxxix).
roman_number(mmmmlxxxv).
roman_number(mcxxi).
roman_number(mdcccxxxvii).
roman_number(mmccclxvii).
roman_number(mcdxxxv).
roman_number(ccxxxiii).
roman_number(cmxx).
roman_number(mmmclxiv).
roman_number(mccclxxxvi).
roman_number(dcccxcviii).
roman_number(mmmdccccxxxiv).
roman_number(cdxviiii).
roman_number(mmccxxxv).
roman_number(mdcccxxxii).
roman_number(mmmmd).
roman_number(mmdcclxix).
roman_number(mmmmccclxxxxvi).
roman_number(mmdccxlii).
roman_number(mmmdcccviiii).
roman_number(dcclxxxiiii).
roman_number(mdccccxxxii).
roman_number(mmcxxvii).
roman_number(dcccxxx).
roman_number(cclxix).
roman_number(mmmxi).
roman_number(mmmmcmlxxxxviii).
roman_number(mmmmdlxxxvii).
roman_number(mmmmdccclx).
roman_number(mmccliv).
roman_number(cmix).
roman_number(mmdccclxxxiiii).
roman_number(clxxxii).
roman_number(mmccccxxxxv).
roman_number(mmmmdlxxxviiii).
roman_number(mmmdcccxxi).
roman_number(mmdcccclxxvi).
roman_number(mcccclxx).
roman_number(mmcdlviiii).
roman_number(mmmdccclix).
roman_number(mmmmccccxix).
roman_number(mmmdccclxxv).
roman_number(xxxi).
roman_number(cdlxxxiii).
roman_number(mmmcxv).
roman_number(mmdcclxiii).
roman_number(mmdxxx).
roman_number(mmmmccclvii).
roman_number(mmmdci).
roman_number(mmmmcdlxxxiiii).
roman_number(mmmmcccxvi).
roman_number(ccclxxxviii).
roman_number(mmmmcml).
roman_number(mmmmxxiv).
roman_number(mmmccccxxx).
roman_number(dccx).
roman_number(mmmcclx).
roman_number(mmdxxxiii).
roman_number(ccclxiii).
roman_number(mmdccxiii).
roman_number(mmmcccxliv).
roman_number(clxxxxi).
roman_number(cxvi).
roman_number(mmmmcxxxiii).
roman_number(clxx).
roman_number(dcccxviii).
roman_number(mlxvii).
roman_number(dlxxxx).
roman_number(mmdxxi).
roman_number(mmmmdlxxxxviii).
roman_number(mxxii).
roman_number(lxi).
roman_number(dccccxliii).
roman_number(mmmmdv).
roman_number(mmmmxxxiv).
roman_number(mdccclviii).
roman_number(mmmcclxxii).
roman_number(mmmmdccxxxvi).
roman_number(mmmmlxxxix).
roman_number(mdccclxxxi).
roman_number(mmmmdcccxv).
roman_number(mmmmccccxi).
roman_number(mmmmcccliii).
roman_number(mdccclxxi).
roman_number(mmccccxi).
roman_number(mlxv).
roman_number(mmcdlxii).
roman_number(mmmmdxxxxii).
roman_number(mmmmdcccxl).
roman_number(mmmmcmlvi).
roman_number(cclxxxiv).
roman_number(mmmdcclxxxvi).
roman_number(mmclii).
roman_number(mmmccccxv).
roman_number(mmlxxxiii).
roman_number(mmmv).
roman_number(mmmv).
roman_number(dcclxii).
roman_number(mmdccccxvi).
roman_number(mmdcxlviii).
roman_number(ccliiii).
roman_number(cccxxv).
roman_number(mmdcclxxxviiii).
roman_number(mmmmdclxxviii).
roman_number(mmmmdcccxci).
roman_number(mmmmcccxx).
roman_number(mmccxlv).
roman_number(mmmdccclxix).
roman_number(mmcclxiiii).
roman_number(mmmdcccxlix).
roman_number(mmmmccclxix).
roman_number(cmlxxxxi).
roman_number(mcmlxxxix).
roman_number(mmcdlxi).
roman_number(mmdclxxviii).
roman_number(mmmmdcclxi).
roman_number(mcdxxv).
roman_number(dl).
roman_number(ccclxxii).
roman_number(mxviiii).
roman_number(mcccclxviii).
roman_number(ciii).
roman_number(mmmdcclxxiiii).
roman_number(mmmdviii).
roman_number(mmmmccclxxxxvii).
roman_number(mmdxxvii).
roman_number(mmdcclxxxxv).
roman_number(mmmmcxlvi).
roman_number(mmmdcclxxxii).
roman_number(mmmdxxxvi).
roman_number(mcxxii).
roman_number(cli).
roman_number(dclxxxix).
roman_number(mmmcli).
roman_number(mdclxiii).
roman_number(mmmmdccxcvii).
roman_number(mmccclxxxv).
roman_number(mmmdcxxviii).
roman_number(mmmcdlx).
roman_number(mmmcmlii).
roman_number(mmmiv).
roman_number(mmmmdccclviii).
roman_number(mmmdlxxxviii).
roman_number(mcxxiv).
roman_number(mmmmlxxvi).
roman_number(clxxix).
roman_number(mmmccccxxviiii).
roman_number(dcclxxxv).
roman_number(mmmdcccvi).
roman_number(li).
roman_number(clxxxvi).
roman_number(mmmmccclxxvi).
roman_number(mccclxvi).
roman_number(ccxxxix).
roman_number(mmdxxxxi).
roman_number(mmdcccxli).
roman_number(dccclxxxviii).
roman_number(mmmmdccciv).
roman_number(mdccccxv).
roman_number(mmcmvi).
roman_number(mmmmcmlxxxxv).
roman_number(mmdcclvi).
roman_number(mmmmccxlviii).
roman_number(dcccciiii).
roman_number(mmcccciii).
roman_number(mmmdcclxxxviiii).
roman_number(mdccclxxxxv).
roman_number(dvii).
roman_number(mmmv).
roman_number(dcxxv).
roman_number(mmdcccxcv).
roman_number(dcviii).
roman_number(mmcdlxvi).
roman_number(mcxxviii).
roman_number(mdccxcviii).
roman_number(mmdclx).
roman_number(mmmdcclxiv).
roman_number(mmcdlxxvii).
roman_number(mmdlxxxiiii).
roman_number(mmmmcccxxii).
roman_number(mmmdcccxliiii).
roman_number(dcccclxvii).
roman_number(mmmclxxxxiii).
roman_number(mccxv).
roman_number(mmmmdcxi).
roman_number(mmmmdclxxxxv).
roman_number(mmmccclii).
roman_number(mmcmix).
roman_number(mmdccxxv).
roman_number(mmdlxxxvi).
roman_number(mmmmdcxxviiii).
roman_number(dccccxxxviiii).
roman_number(mmccxxxiiii).
roman_number(mmdcclxxviii).
roman_number(mdcclxviiii).
roman_number(mmcclxxxv).
roman_number(mmmmdccclxxxviii).
roman_number(mmcmxci).
roman_number(mdxlii).
roman_number(mmmmdccxiv).
roman_number(mmmmli).
roman_number(dxxxxiii).
roman_number(mmdccxi).
roman_number(mmmmcclxxxiii).
roman_number(mmmdccclxxiii).
roman_number(mdclvii).
roman_number(mmcd).
roman_number(mcccxxvii).
roman_number(mmmmdcciiii).
roman_number(mmmdccxlvi).
roman_number(mmmclxxxvii).
roman_number(mmmccviiii).
roman_number(mcccclxxix).
roman_number(dl).
roman_number(dccclxxvi).
roman_number(mmdxci).
roman_number(mmmmdccccxxxvi).
roman_number(mmcii).
roman_number(mmmdcccxxxxv).
roman_number(mmmcdxlv).
roman_number(mmdcxxxxiv).
roman_number(mmd).
roman_number(mdccclxxxx).
roman_number(mmdcxliii).
roman_number(mmccxxxii).
roman_number(mmdcxxxxviiii).
roman_number(dccclxxi).
roman_number(mdxcviiii).
roman_number(mmmmcclxxviii).
roman_number(mdclviiii).
roman_number(mmmccclxxxix).
roman_number(mdclxxxv).
roman_number(mdlviii).
roman_number(mmmmccvii).
roman_number(mmmmdcxiv).
roman_number(mmmccclxiiii).
roman_number(mmiiii).
roman_number(mmmmccclxxiii).
roman_number(cciii).
roman_number(mmmcclv).
roman_number(mmmdxiii).
roman_number(mmmcccxc).
roman_number(mmmdcccxxi).
roman_number(mmmmccccxxxii).
roman_number(ccclvi).
roman_number(mmmccclxxxvi).
roman_number(mxviiii).
roman_number(mmmccccxiiii).
roman_number(clxvii).
roman_number(mmmcclxx).
roman_number(cccclxiv).
roman_number(mmxxxxii).
roman_number(mmmmcclxxxx).
roman_number(mxl).
roman_number(ccxvi).
roman_number(cccclviiii).
roman_number(mmcccii).
roman_number(mccclviii).
roman_number(mmmmcccx).
roman_number(mcdlxxxxiv).
roman_number(mdcccxiii).
roman_number(mmdcccxl).
roman_number(mmmmcccxxiii).
roman_number(dxxxiv).
roman_number(cvi).
roman_number(mmmmdclxxx).
roman_number(dcccvii).
roman_number(mmcmlxiiii).
roman_number(mmmdcccxxxiii).
roman_number(dccc).
roman_number(mdiii).
roman_number(mmccclxvi).
roman_number(mmmcccclxxi).
roman_number(mmdccccxviii).
roman_number(ccxxxvii).
roman_number(cccxxv).
roman_number(mdcccxii).
roman_number(mmmcmv).
roman_number(mmmmcmxv).
roman_number(mmmmdcxci).
roman_number(dxxi).
roman_number(mmccxlviiii).
roman_number(mmmmcmlii).
roman_number(mdlxxx).
roman_number(mmdclxvi).
roman_number(cxxi).
roman_number(mmmdcccliiii).
roman_number(mmmcxxi).
roman_number(mcciii).
roman_number(mmdcxxxxi).
roman_number(ccxcii).
roman_number(mmmmdxxxv).
roman_number(mmmccclxv).
roman_number(mmmmdlxv).
roman_number(mmmccccxxxii).
roman_number(mmmcccviii).
roman_number(dcccclxxxxii).
roman_number(mmclxiv).
roman_number(mmmmcxi).
roman_number(mlxxxxvii).
roman_number(mmmcdxxxviii).
roman_number(mdxxii).
roman_number(mlv).
roman_number(mmmmdlxvi).
roman_number(mmmcxii).
roman_number(xxxiii).
roman_number(mmmmdcccxxvi).
roman_number(mmmlxviiii).
roman_number(mmmlx).
roman_number(mmmcdlxvii).
roman_number(mdccclvii).
roman_number(mmcxxxvii).
roman_number(mdccccxxx).
roman_number(mmdccclxiii).
roman_number(mmmmdcxlix).
roman_number(mmmmcmxlviii).
roman_number(dccclxxviiii).
roman_number(mdcccliii).
roman_number(mmmcmlxi).
roman_number(mmmmcclxi).
roman_number(mmdcccliii).
roman_number(mmmdcccvi).
roman_number(mmdxxxxix).
roman_number(mmclxxxxv).
roman_number(mmdxxx).
roman_number(mmmxiii).
roman_number(dclxxix).
roman_number(dcclxii).
roman_number(mmmmdcclxviii).
roman_number(mdccxxxxiii).
roman_number(ccxxxii).
roman_number(mmmmdcxxv).
roman_number(mmmcccxxviii).
roman_number(mdcviii).
roman_number(mmmclxxxxiiii).
roman_number(clxxxi).
roman_number(mdccccxxxiii).
roman_number(mmmmdcxxx).
roman_number(mmmdcxxiv).
roman_number(mmmccxxxvii).
roman_number(mcccxxxxiiii).
roman_number(cxviii).
roman_number(mmdcccciv).
roman_number(mmmmcdlxxv).
roman_number(mmmdlxiv).
roman_number(mdxciii).
roman_number(mcclxxxi).
roman_number(mmmdcccxxiv).
roman_number(mcxliii).
roman_number(mmmdccci).
roman_number(mcclxxx).
roman_number(ccxv).
roman_number(mmdcclxxi).
roman_number(mmdlxxxiii).
roman_number(mmmmdcxvii).
roman_number(mmmcmlxv).
roman_number(mclxviii).
roman_number(mmmmcclxxvi).
roman_number(mmmdcclxviiii).
roman_number(mmmmdcccix).
roman_number(dlxxxxix).
roman_number(dcccxxii).
roman_number(mmmmiii).
roman_number(mmmmccclxxvi).
roman_number(dcccxciii).
roman_number(dxxxi).
roman_number(mxxxiiii).
roman_number(ccxii).
roman_number(mmmdcclxxxiiii).
roman_number(mmmcxx).
roman_number(mmmcmxxvii).
roman_number(dcccxxxx).
roman_number(mmcdxxxviiii).
roman_number(mmmmdccxviii).
roman_number(lv).
roman_number(mmmdccccvi).
roman_number(mcccii).
roman_number(mmcmlxviiii).
roman_number(mdccxi).
roman_number(mmmmdlxvii).
roman_number(mmcccclxi).
roman_number(mmdccv).
roman_number(mmmcccxxxiiii).
roman_number(mmmmdi).
roman_number(mmmdcccxcv).
roman_number(mmdcclxxxxi).
roman_number(mmmdxxvi).
roman_number(mmmdccclvi).
roman_number(mmdcxxx).
roman_number(mcccvii).
roman_number(mmmmccclxii).
roman_number(mmmmxxv).
roman_number(mmcmxxv).
roman_number(mmlvi).
roman_number(mmdxxx).
roman_number(mmmmcvii).
roman_number(mdc).
roman_number(mcciii).
roman_number(mmmmdcc).
roman_number(mmcclxxv).
roman_number(mmdcccxxxxvi).
roman_number(mmmmccclxv).
roman_number(cdxiiii).
roman_number(mlxiiii).
roman_number(ccv).
roman_number(mmmcmxxxi).
roman_number(cccclxvi).
roman_number(mdxxxii).
roman_number(mmmmccclviii).
roman_number(mmv).
roman_number(mmmclii).
roman_number(mcmli).
roman_number(mmdccxx).
roman_number(mmmmccccxxxvi).
roman_number(mcclxxxi).
roman_number(mmmcmvi).
roman_number(dccxxx).
roman_number(mmmmccclxv).
roman_number(dcccxi).
roman_number(mmmmdcccxiv).
roman_number(cccxxi).
roman_number(mmdlxxv).
roman_number(cccclxxxx).
roman_number(mccclxxxxii).
roman_number(mmdcix).
roman_number(dccxliiii).
roman_number(dxiv).
roman_number(mmmmclii).
roman_number(cdlxi).
roman_number(mmmcxxvii).
roman_number(mmmmdcccclxiii).
roman_number(mmmdcliiii).
roman_number(mccccxxxxii).
roman_number(mmccclx).
roman_number(ccccliii).
roman_number(mdcclxxvi).
roman_number(mcmxxiii).
roman_number(mmmmdlxxviii).
roman_number(mmdcccclx).
roman_number(mmmccclxxxx).
roman_number(mmmcdxxvi).
roman_number(mmmdlviii).
roman_number(ccclxi).
roman_number(mmmmdcxxii).
roman_number(mmdcccxxi).
roman_number(mmdccxiii).
roman_number(mmmmclxxxvi).
roman_number(mdccccxxvi).
roman_number(mdv).
roman_number(mmdcccclxxvi).
roman_number(mmmmccxxxvii).
roman_number(mmmdcclxxviiii).
roman_number(mmmcccclxvii).
roman_number(dccxli).
roman_number(mmclxxxviii).
roman_number(mccxxxvi).
roman_number(mmdcxlviii).
roman_number(mmmmcxxxii).
roman_number(mmmmdcclxvi).
roman_number(mmmmcmli).
roman_number(mmmmclxv).
roman_number(mmmmdcccxciv).
roman_number(mcclxxvii).
roman_number(lxxviiii).
roman_number(dcclii).
roman_number(mmmcccxcvi).
roman_number(mmmclv).
roman_number(mmdcccxxxxviii).
roman_number(dcccxv).
roman_number(mxc).
roman_number(mmdcclxxxxvii).
roman_number(mmmmcml).
roman_number(mmdccclxxviii).
roman_number(dxxi).
roman_number(mcccxli).
roman_number(dclxxxxi).
roman_number(mmccclxxxxviii).
roman_number(mdcccclxxviii).
roman_number(mmmmdxxv).
roman_number(mmmdcxxxvi).
roman_number(mmmcmxcvii).
roman_number(mmxviiii).
roman_number(mmmdcclxxiv).
roman_number(mmmcxxv).
roman_number(dxxxviii).
roman_number(mmmmclxvi).
roman_number(mdxii).
roman_number(mmccclxx).
roman_number(cclxxi).
roman_number(dxiv).
roman_number(mmmcliii).
roman_number(dlii).
roman_number(mmmcccxlix).
roman_number(mmccccxxvi).
roman_number(mmdcxliii).
roman_number(mxxxxii).
roman_number(ccclxxxv).
roman_number(mdclxxvi).
roman_number(mdcxii).
roman_number(mmmccclxxxiii).
roman_number(mmdcccclxxxii).
roman_number(mmmmccclxxxv).
roman_number(mmdcxxi).
roman_number(dcccxxx).
roman_number(mmmdcccclii).
roman_number(mmmdccxxii).
roman_number(mmmmcdxcviii).
roman_number(mmmcclxviiii).
roman_number(mmxxv).
roman_number(mmmmcdxix).
roman_number(mmmmcccx).
roman_number(mmmcccclxvi).
roman_number(mmmmdclxxviiii).
roman_number(mmmmdcxxxxiv).
roman_number(mmmcmxii).
roman_number(mmmmxxxiii).
roman_number(mmmmdlxxxii).
roman_number(dcccliv).
roman_number(mdxviiii).
roman_number(mmmclxxxxv).
roman_number(ccccxx).
roman_number(mmdix).
roman_number(mmcmlxxxviii).
roman_number(dccxliii).
roman_number(dcclx).
roman_number(d).
roman_number(mcccvii).
roman_number(mmmmccclxxxiii).
roman_number(mdccclxxiiii).
roman_number(mmmdcccclxxxvii).
roman_number(mmmmcccvii).
roman_number(mmmdcclxxxxvi).
roman_number(cdxxxiv).
roman_number(mcclxviii).
roman_number(mmmmdlx).
roman_number(mmmmdxii).
roman_number(mmmmccccliiii).
roman_number(mcmlxxxxiii).
roman_number(mmmmdccciii).
roman_number(mmdclxxxiii).
roman_number(mdcccxxxxiv).
roman_number(xxxxvii).
roman_number(mmmdcccxxxii).
roman_number(mmmdcccxlii).
roman_number(mcxxxv).
roman_number(mdcxxviiii).
roman_number(mmmcxxxxiiii).
roman_number(mmmmcdxvii).
roman_number(mmmdxxiii).
roman_number(mmmmcccclxi).
roman_number(dclxxxxviiii).
roman_number(lxxxxi).
roman_number(cxxxiii).
roman_number(mcdx).
roman_number(mcclvii).
roman_number(mdcxxxxii).
roman_number(mmmcxxiv).
roman_number(mmmmlxxxx).
roman_number(mmdccccxlv).
roman_number(mlxxx).
roman_number(mmdcccclx).
roman_number(mcdliii).
roman_number(mmmccclxvii).
roman_number(mmmmccclxxiv).
roman_number(mmmdcviii).
roman_number(dccccxxiii).
roman_number(mmxci).
roman_number(mmdcciv).
roman_number(mmmmdcccxxxiv).
roman_number(ccclxxi).
roman_number(mcclxxxii).
roman_number(mcmiii).
roman_number(ccxxxi).
roman_number(dccxxxviii).
roman_number(mmmmdccxlviiii).
roman_number(mmmmcmxxxv).
roman_number(dccclxxv).
roman_number(dccxci).
roman_number(mmmmdvii).
roman_number(mmmmdccclxviiii).
roman_number(cccxcv).
roman_number(mmmmdccxx).
roman_number(mccccii).
roman_number(mmmcccxc).
roman_number(mmmcccii).
roman_number(mmdcclxxvii).
roman_number(mmdcliiii).
roman_number(ccxliii).
roman_number(mmmdcxviii).
roman_number(mmmcccix).
roman_number(mcxv).
roman_number(mmccxxv).
roman_number(mlxxiiii).
roman_number(mdccxxvi).
roman_number(mmmcccxx).
roman_number(mmdlxx).
roman_number(mmccccvi).
roman_number(mmdccxx).
roman_number(mmmmdccccxcv).
roman_number(mdcccxxxii).
roman_number(mmmmdccccxxxx).
roman_number(xciv).
roman_number(mmcccclx).
roman_number(mmxvii).
roman_number(mlxxi).
roman_number(mmmdxxviii).
roman_number(mdccccii).
roman_number(mmmcmlvii).
roman_number(mmclxxxxviii).
roman_number(mdcccclv).
roman_number(mcccclxxiiii).
roman_number(mccclii).
roman_number(mcdxlvi).
roman_number(mmmmdxviii).
roman_number(dcclxxxix).
roman_number(mmmdcclxiv).
roman_number(mdccccxliii).
roman_number(clxxxxv).
roman_number(mmmmccxxxvi).
roman_number(mmmdcccxxi).
roman_number(mmmmcdlxxvii).
roman_number(mcdliii).
roman_number(mmccxlvi).
roman_number(dccclv).
roman_number(mcdlxx).
roman_number(dclxxviii).
roman_number(mmdcxxxix).
roman_number(mmmmdclx).
roman_number(mmdccli).
roman_number(mmcxxxv).
roman_number(mmmccxii).
roman_number(mmmmcmlxii).
roman_number(mmmmccv).
roman_number(mcccclxix).
roman_number(mmmmcciii).
roman_number(clxvii).
roman_number(mccclxxxxiiii).
roman_number(mmmmdcviii).
roman_number(mmdccclxi).
roman_number(mmlxxix).
roman_number(cmlxix).
roman_number(mmdcccxlviiii).
roman_number(dclxii).
roman_number(mmmcccxlvii).
roman_number(mdcccxxxv).
roman_number(mmmmdccxcvi).
roman_number(dcxxx).
roman_number(xxvi).
roman_number(mmlxix).
roman_number(mmcxi).
roman_number(dcxxxvii).
roman_number(mmmmcccxxxxviii).
roman_number(mmmmdclxi).
roman_number(mmmmdclxxiiii).
roman_number(mmmmviii).
roman_number(mmmmdccclxii).
roman_number(mdcxci).
roman_number(mmcccxxiiii).
roman_number(ccccxxxxv).
roman_number(mmdcccxxi).
roman_number(mcvi).
roman_number(mmdcclxviii).
roman_number(mmmmcxl).
roman_number(mlxviii).
roman_number(cmxxvii).
roman_number(ccclv).
roman_number(mdcclxxxix).
roman_number(mmmcccclxv).
roman_number(mmdcclxii).
roman_number(mdlxvi).
roman_number(mmmcccxviii).
roman_number(mmmmcclxxxi).
roman_number(mmcxxvii).
roman_number(mmdccclxviii).
roman_number(mmmcxcii).
roman_number(mmmmdclviii).
roman_number(mmmmdcccxxxxii).
roman_number(mmdcccclxxxxvi).
roman_number(mdccxl).
roman_number(mdcclvii).
roman_number(mmmmdccclxxxvi).
roman_number(dccxxxiii).
roman_number(mmmmdcccclxxxv).
roman_number(mmccxxxxviii).
roman_number(mmmcclxxviii).
roman_number(mmmdclxxviii).
roman_number(dccci).
roman_number(mmmmlxxxxviiii).
roman_number(mmmcccclxxii).
roman_number(mmclxxxvii).
roman_number(cclxvi).
roman_number(mcdxliii).
roman_number(mmcxxviii).
roman_number(mdxiv).
roman_number(cccxcviii).
roman_number(clxxviii).
roman_number(mmcxxxxviiii).
roman_number(mmmdclxxxiv).
roman_number(cmlviii).
roman_number(mcdlix).
roman_number(mmmmdcccxxxii).
roman_number(mmmmdcxxxiiii).
roman_number(mdcxxi).
roman_number(mmmdcxlv).
roman_number(mclxxviii).
roman_number(mcdxxii).
roman_number(iv).
roman_number(mcdlxxxxiii).
roman_number(mmmmdcclxv).
roman_number(ccli).
roman_number(mmmmdcccxxxviii).
roman_number(dclxii).
roman_number(mccclxvii).
roman_number(mmmmdcccxxxvi).
roman_number(mmdccxli).
roman_number(mlxi).
roman_number(mmmcdlxviii).
roman_number(mccccxciii).
roman_number(xxxiii).
roman_number(mmmdclxiii).
roman_number(mmmmdcl).
roman_number(dcccxxxxiiii).
roman_number(mmdlvii).
roman_number(dxxxvii).
roman_number(mccccxxiiii).
roman_number(mcvii).
roman_number(mmmmdccxl).
roman_number(mmmmcxxxxiiii).
roman_number(mccccxxiv).
roman_number(mmclxviii).
roman_number(mmxciii).
roman_number(mdcclxxx).
roman_number(mcccliiii).
roman_number(mmdclxxi).
roman_number(mxi).
roman_number(mcmliv).
roman_number(mmmcciiii).
roman_number(dcclxxxviiii).
roman_number(mdcliv).
roman_number(mmmdcxix).
roman_number(cmlxxxi).
roman_number(dcclxxxvii).
roman_number(xxv).
roman_number(mmmxxxvi).
roman_number(mdviiii).
roman_number(clxiii).
roman_number(mmmcdlviiii).
roman_number(mmccccvii).
roman_number(mmmlxx).
roman_number(mxxxxii).
roman_number(mmmmccclxviii).
roman_number(mmdcccxxviii).
roman_number(mmmmdcxxxxi).
roman_number(mmmmdcccxxxxv).
roman_number(mmmxv).
roman_number(mmmmccxviiii).
roman_number(mmdccxiiii).
roman_number(mmmxxvii).
roman_number(mdcclviiii).
roman_number(mmcxxiiii).
roman_number(mccclxxiv).
roman_number(dclviii).
roman_number(mmmlvii).
roman_number(mmmcxlv).
roman_number(mmxcvii).
roman_number(mmmccclxxxvii).
roman_number(mmmmccxxii).
roman_number(dxii).
roman_number(mmmdlv).
roman_number(mccclxxviii).
roman_number(mmmcliiii).
roman_number(mmmmclxxxx).
roman_number(mmmclxxxiiii).
roman_number(mdcxxiii).
roman_number(mmmmccxvi).
roman_number(mmmmdlxxxiii).
roman_number(mmmdxxxxiii).
roman_number(mmmmcccclv).
roman_number(mmmdlxxxi).
roman_number(mmmcclxxvi).
roman_number(mmmmxx).
roman_number(mmmmdlvi).
roman_number(mcccclxxx).
roman_number(mmmxxii).
roman_number(mmxxii).
roman_number(mmdccccxxxi).
roman_number(mmmdxxv).
roman_number(mmmdclxxxviiii).
roman_number(mmmdlxxxxvii).
roman_number(mdlxiiii).
roman_number(cmxc).
roman_number(mmmxxxviii).
roman_number(mdlxxxviii).
roman_number(mccclxxvi).
roman_number(mmcdlix).
roman_number(mmdcccxviii).
roman_number(mdcccxxxxvi).
roman_number(mmmmcmiv).
roman_number(mmmmdciiii).
roman_number(mmccxxxv).
roman_number(xxxxvi).
roman_number(mmmmccxvii).
roman_number(mmccxxiv).
roman_number(mcmlviiii).
roman_number(mlxxxix).
roman_number(mmmmlxxxix).
roman_number(clxxxxix).
roman_number(mmmdcccclviii).
roman_number(mmmmcclxxiii).
roman_number(mcccc).
roman_number(dccclix).
roman_number(mmmccclxxxii).
roman_number(mmmcclxviiii).
roman_number(mclxxxv).
roman_number(cdlxxxvii).
roman_number(dcvi).
roman_number(mmx).
roman_number(mmccxiii).
roman_number(mmmmdcxx).
roman_number(mmmmxxviii).
roman_number(dccclxii).
roman_number(mmmmcccxliii).
roman_number(mmmmclxv).
roman_number(dxci).
roman_number(mmmmclxxx).
roman_number(mmmdccxxxxi).
roman_number(mmmmxxxxvi).
roman_number(dclx).
roman_number(mmmcccxi).
roman_number(mcclxxx).
roman_number(mmcdlxxii).
roman_number(dcclxxi).
roman_number(mmmcccxxxvi).
roman_number(mcccclxxxviiii).
roman_number(cdlviii).
roman_number(dcclvi).
roman_number(mmmmdcxxxviii).
roman_number(mmccclxxxiii).
roman_number(mmmmdcclxxv).
roman_number(mmmxxxvi).
roman_number(ccclxxxxix).
roman_number(cv).
roman_number(ccccxiii).
roman_number(ccccxvi).
roman_number(mdccclxxxiiii).
roman_number(mmdcclxxxii).
roman_number(mmmmcccclxxxi).
roman_number(mxxv).
roman_number(mmccclxxviiii).
roman_number(mmmccxii).
roman_number(mmmmccxxxiii).
roman_number(mmccclxxxvi).
roman_number(mmmdccclviiii).
roman_number(mccxxxvii).
roman_number(mdclxxv).
roman_number(xxxv).
roman_number(mmdli).
roman_number(mmmccxxx).
roman_number(mmmmcxxxxv).
roman_number(cccclix).
roman_number(mmmmdccclxxiii).
roman_number(mmcccxvii).
roman_number(dcccxvi).
roman_number(mmmcccxxxxv).
roman_number(mdccccxcv).
roman_number(clxxxi).
roman_number(mmmmdcclxx).
roman_number(mmmdccciii).
roman_number(mmclxxvii).
roman_number(mmmdccxxix).
roman_number(mmdcccxciiii).
roman_number(mmmcdxxiiii).
roman_number(mmmmxxviii).
roman_number(mmmmdcccclxviii).
roman_number(mdcccxx).
roman_number(mmmmcdxxi).
roman_number(mmmmdlxxxix).
roman_number(ccxvi).
roman_number(mdviii).
roman_number(mmcclxxi).
roman_number(mmmdccclxxi).
roman_number(mmmccclxxvi).
roman_number(mmcclxi).
roman_number(mmmmdcccxxxiv).
roman_number(dlxxxvi).
roman_number(mmmmdxxxii).
roman_number(mmmxxiiii).
roman_number(mmmmcdiv).
roman_number(mmmmcccxlviii).
roman_number(mmmmcxxxviii).
roman_number(mmmccclxvi).
roman_number(mdccxviii).
roman_number(mmcxx).
roman_number(ccclix).
roman_number(mmmmdcclxxii).
roman_number(mdccclxxv).
roman_number(mmmmdcccxxiv).
roman_number(dcccxxxxviii).
roman_number(mmmdccccxxxviiii).
roman_number(mmmmccxxxv).
roman_number(mdclxxxiii).
roman_number(mmcclxxxiv).
roman_number(mclxxxxiiii).
roman_number(dxxxxiii).
roman_number(mcccxxxxviii).
roman_number(mmclxxix).
roman_number(mmmmcclxiv).
roman_number(mxxii).
roman_number(mmmcxix).
roman_number(mdcxxxvii).
roman_number(mmdccvi).
roman_number(mclxxxxviii).
roman_number(mmmcxvi).
roman_number(mccclx).
roman_number(mmmcdx).
roman_number(cclxviiii).
roman_number(mmmcclx).
roman_number(mcxxviii).
roman_number(lxxxii).
roman_number(mcccclxxxi).
roman_number(mmmi).
roman_number(mmmccclxiv).
roman_number(mmmcccxxviiii).
roman_number(cxxxviii).
roman_number(mmcccxx).
roman_number(mmmccxxviiii).
roman_number(mcclxvi).
roman_number(mmmccccxxxxvi).
roman_number(mmdccxcix).
roman_number(mcmlxxi).
roman_number(mmcclxviii).
roman_number(cdlxxxxiii).
roman_number(mmmmdccxxii).
roman_number(mmmmdcclxxxvii).
roman_number(mmmdccliv).
roman_number(mmcclxiii).
roman_number(mdxxxvii).
roman_number(dccxxxiiii).
roman_number(mcii).
roman_number(mmmdccclxxi).
roman_number(mmmlxxiii).
roman_number(mdcccliii).
roman_number(mmxxxviii).
roman_number(mdccxviiii).
roman_number(mdccccxxxvii).
roman_number(mmcccxvi).
roman_number(mcmxxii).
roman_number(mmmccclviii).
roman_number(mmmmdcccxx).
roman_number(mcxxiii).
roman_number(mmmdlxi).
roman_number(mmmmdxxii).
roman_number(mdcccx).
roman_number(mmdxcviiii).
roman_number(mmmdccccviii).
roman_number(mmmmdccccxxxxvi).
roman_number(mmdcccxxxv).
roman_number(mmcxciv).
roman_number(mcmlxxxxiii).
roman_number(mmmccclxxvi).
roman_number(mmmmdclxxxv).
roman_number(cmlxix).
roman_number(dcxcii).
roman_number(mmxxviii).
roman_number(mmmmcccxxx).
roman_number(xxxxviiii).